# Generated by Django 4.2.29 on 2026-05-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_seed_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('in_person', 'In-Person'), ('virtual', 'Virtual')], default='in_person', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_room_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
